#
# Test job to see how packaging looks like.
#

name: Build distributions

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python -m pip install -U pip
          pip install build

      - run: python -m build --wheel -vv
      - if: matrix.os == 'ubuntu-latest'
        run: python -m build --sdist -vv
        # We only need a single source distribution

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          retention-days: 1
          path: dist

  make_artifact:
    name: Combine artifacts
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
      # Download all artifacts so far
    - uses: actions/upload-artifact@v4
      with:
        name: package-all
        path: dist
