#
# Test job to see how packaging looks like.
#

name: Build distributions

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python -m pip install -U pip
          pip install build

      - run: python -m build --wheel -vv
      - if: matrix.os == 'ubuntu-latest'
        run: python -m build --sdist -vv
        # We only need a single source distribution

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          retention-days: 1
          path: dist

  make_artifact:
    name: Combine artifacts
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
      # Download all artifacts so far
    - uses: actions/upload-artifact@v4
      with:
        name: package-all
        path: dist

  test_artifacts:
    name: Test distributions
    needs: make_artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        # Can't really test with Windows because 'TcAdsDll.dll' will be missing

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package-all
          path: dist

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Now install the package from the local wheels and try to use it:
      - run: |
          pip install pyads --no-index --find-links ./dist
          python -c "import pyads; pyads.Connection(ams_net_id='127.0.0.1.1.1', ams_net_port=851)" 

  test_editable:
    name: Test editable install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          pip install -e . -vv
          python -c "import pyads; pyads.Connection(ams_net_id='127.0.0.1.1.1', ams_net_port=851)"
